#!/bin/bash
#ch_7 
path=$(pwd)



function GETTEXT (){
    cd $path/sources/
    tar -xvf gettext-0.21.1.tar.xz
    cd $path/sources/gettext-0.21.1
    ./configure --disable-shared
    make
    cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
    rm -rf $path/sources/gettext-0.21.1

}

function BISON(){
 cd $path/sources/
 tar -xvf bison-3.8.2.tar.xz
 cd $path/sources/bison-3.8.2
 ./configure --prefix=/usr \
--docdir=/usr/share/doc/bison-3.8.2
make
make install
rm -rf $path/sources/bison-3.8.2 
}

function PERL(){
 cd $path/sources/
 tar -xvf perl-5.36.0.tar.xz
 cd $path/sources/perl-5.36.0
 sh Configure -des \
 -Dprefix=/usr \
 -Dvendorprefix=/usr \
 -Dprivlib=/usr/lib/perl5/5.36/core_perl \
 -Darchlib=/usr/lib/perl5/5.36/core_perl \
 -Dsitelib=/usr/lib/perl5/5.36/site_perl \
 -Dsitearch=/usr/lib/perl5/5.36/site_perl \
 -Dvendorlib=/usr/lib/perl5/5.36/vendor_perl \
 -Dvendorarch=/usr/lib/perl5/5.36/vendor_perl
make
make install
rm -rf $path/sources/perl-5.36.0 
}

function PYTHON(){
cd $path/sources/
 tar -xvf python-3.11.2-docs-html.tar.bz2
 cd $path/sources/python-3.11.2-docs-html
 ./configure --prefix=/usr \
 --enable-shared \
 --without-ensurepip


make
make install
rm -rf $path/sources/python-3.11.2-docs-html
}
function TEX(){
cd $path/sources/
 tar -xvf texinfo-7.0.2.tar.xz
 cd $path/sources/texinfo-7.0.2
 ./configure --prefix=/usr
 make
 make install
 rm -rf $path/sources/texinfo-7.0.2
 }
function UTI(){
cd $path/sources/
 tar -xvf util-linux-2.38.1.tar.xz
 cd $path/sources/util-linux-2.38.1
 mkdir -pv /var/lib/hwclock
 ./configure ADJTIME_PATH=/var/lib/hwclock/adjtime \
 --libdir=/usr/lib \
 --docdir=/usr/share/doc/util-linux-2.38.1 \
 --disable-chfn-chsh \
 --disable-login \
 --disable-nologin \
 --disable-su \
 --disable-setpriv \
 --disable-runuser \
 --disable-pylibmount \
 --disable-static \
 --without-python \
 runstatedir=/run
make
make install
rm -rf $path/sources/util-linux-2.38.1
    }
