#!/bin/bash
#ch_7 


path=$(pwd)



function GETTEXT (){ 
S1=$(date +%S ) 
h1=$(date +%H ) 
M1=$(date +%M ) 

    cd /sources/
    tar -xvf gettext-0.21.1.tar.xz
    cd /sources/gettext-0.21.1
    ./configure --disable-shared
    make
    cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
    rm -rf /sources/gettext-0.21.1
h2=$(date +%H ) 
M2=$(date +%M ) 
S2=$(date +%S ) 
echo "${FUNCNAME[0]} is finished $((h1-h2))hour $((M1-M2))minutes $((S1- S2 ))seconds" >> /finish.txt


}

function BISON(){ 
S1=$(date +%S ) 
h1=$(date +%H ) 
M1=$(date +%M ) 

 cd /sources/
 tar -xvf bison-3.8.2.tar.xz
 cd /sources/bison-3.8.2
 ./configure --prefix=/usr \
--docdir=/usr/share/doc/bison-3.8.2
make
make install
rm -rf /sources/bison-3.8.2 
h2=$(date +%H ) 
M2=$(date +%M ) 
S2=$(date +%S ) 
echo "${FUNCNAME[0]} is finished $((h1-h2))hour $((M1-M2))minutes $((S1- S2 ))seconds" >> /finish.txt


}

function PERL(){ 
S1=$(date +%S ) 
h1=$(date +%H ) 
M1=$(date +%M ) 

 cd /sources/
 tar -xvf perl-5.36.0.tar.xz
 cd /sources/perl-5.36.0
 sh Configure -des \
 -Dprefix=/usr \
 -Dvendorprefix=/usr \
 -Dprivlib=/usr/lib/perl5/5.36/core_perl \
 -Darchlib=/usr/lib/perl5/5.36/core_perl \
 -Dsitelib=/usr/lib/perl5/5.36/site_perl \
 -Dsitearch=/usr/lib/perl5/5.36/site_perl \
 -Dvendorlib=/usr/lib/perl5/5.36/vendor_perl \
 -Dvendorarch=/usr/lib/perl5/5.36/vendor_perl
make
make install
rm -rf /sources/perl-5.36.0 
h2=$(date +%H ) 
M2=$(date +%M ) 
S2=$(date +%S ) 
echo "${FUNCNAME[0]} is finished $((h1-h2))hour $((M1-M2))minutes $((S1- S2 ))seconds" >> /finish.txt


}

function PYTHON(){ 
S1=$(date +%S ) 
h1=$(date +%H ) 
M1=$(date +%M ) 

cd /sources/
 tar -xvf python-3.11.2-docs-html.tar.bz2
 cd /sources/python-3.11.2-docs-html
 ./configure --prefix=/usr \
 --enable-shared \
 --without-ensurepip


make
make install
rm -rf /sources/python-3.11.2-docs-html
echo " echo ${FUNCNAME[0]} is finished $(time). " >> finished.log
}
function TEX(){ 
S1=$(date +%S ) 
h1=$(date +%H ) 
M1=$(date +%M ) 

cd /sources/
 tar -xvf texinfo-7.0.2.tar.xz
 cd /sources/texinfo-7.0.2
 ./configure --prefix=/usr
 make
 make install
 rm -rf /sources/texinfo-7.0.2
 h2=$(date +%H ) 
M2=$(date +%M ) 
S2=$(date +%S ) 
echo "${FUNCNAME[0]} is finished $((h1-h2))hour $((M1-M2))minutes $((S1- S2 ))seconds" >> /finish.txt




 }


function UTI(){ 
S1=$(date +%S ) 
h1=$(date +%H ) 
M1=$(date +%M ) 

cd /sources/
 tar -xvf util-linux-2.38.1.tar.xz
 cd /sources/util-linux-2.38.1
 mkdir -pv /var/lib/hwclock
 ./configure ADJTIME_PATH=/var/lib/hwclock/adjtime \
 --libdir=/usr/lib \
 --docdir=/usr/share/doc/util-linux-2.38.1 \
 --disable-chfn-chsh \
 --disable-login \
 --disable-nologin \
 --disable-su \
 --disable-setpriv \
 --disable-runuser \
 --disable-pylibmount \
 --disable-static \
 --without-python \
 runstatedir=/run
make
make install
rm -rf /sources/util-linux-2.38.1
h2=$(date +%H ) 
M2=$(date +%M ) 
S2=$(date +%S ) 
echo "${FUNCNAME[0]} is finished $((h1-h2))hour $((M1-M2))minutes $((S1- S2 ))seconds" >> /finish.txt


   

    }
